variables:
  nightly: nightly-2020-02-01
  RUSTFLAGS:

jobs:

  # Test crates
  - template: ci/azure-test.yml
    parameters:
      name: test_eir
      displayName: Test Eir
      rust: $(nightly)
      cross: true
      crates:
        util/libeir_util_binary: []
        util/libeir_util_datastructures: []
        util/libeir_util_number: []
        util/libeir_util_parse: []
        util/libeir_util_parse_listing: []
        util/libeir_util_pattern_compiler: []
        libeir_intern: []
        libeir_diagnostics: []
        libeir_interpreter: []
        libeir_ir: []
        libeir_passes: []
        libeir_lowerutils: []
        libeir_syntax_erl: []
        libeir_tests: []
